### ISSUE TITLE
WSA 2306.40000.4.0 is out

### ISSUE THREAD

**Issue by Almighty188** [MustardChef/WSAPackages#1]
### Is your feature request related to a problem? Please describe

2306.40000.4.0 is out

### Describe the solution you'd like

Someone to upload 2306.40000.4.0

### Please specify the version of Windows Subsystem for Android

2306.40000.4.0

**Comment by MustardChef** [comment]
@Almighty188 Thank you for telling me. I keep forgetting to check.

**Comment by MustardChef** [comment]
> ### Is your feature request related to a problem? Please describe
> 
> 2306.40000.4.0 is out
> ### Describe the solution you'd like
> 
> Someone to upload 2306.40000.4.0
> ### Describe alternatives you've considered
> 
> _No response_
> ### Please specify the version of Windows Subsystem for Android
> 
> 2306.40000.4.0

Uploaded!

Thank you for telling that the new update had dropped.

**Comment by Almighty188** [comment]
Thanks @MustardChef for providing the archive as always.  I posted about 3.0 just this AM and someone already tells me that on Beta Insiders, 4.0 was already available.   Wished they provided a changelog as 3.0 probably had some bugs for 4.0 to come out this quick afterwards.
