### ISSUE TITLE
WSA v2308.40000.2.0 is out

### ISSUE THREAD

**Issue by Almighty188** [MustardChef/WSAPackages#4]
### Is your feature request related to a problem? Please describe

WSA v2308.40000.2.0 is out per https://www.elevenforum.com/t/windows-subsystem-for-android-wsa-2308-40000-2-0-update-on-windows-11.17741/#post-342297

### Describe the solution you'd like

Finding and providing the download package here.  Thanks as always!

### Describe alternatives you've considered

N/A

### Please specify the version of Windows Subsystem for Android

2308.40000.2.0

**Comment by MustardChef** [comment]
Thank you for the prompt issue, whenever I miss an update.

**Comment by Almighty188** [comment]
Thank you for finding the file!
