### ISSUE TITLE
WSA version 2308.40000.3.0​ is out!

### ISSUE THREAD

**Issue by Almighty188** [MustardChef/WSAPackages#5]
### Is your feature request related to a problem? Please describe

Per https://www.elevenforum.com/t/windows-subsystem-for-android-wsa-2308-40000-3-0-update-on-windows-11.17741/#post-344665 - WSA version 2308.40000.3.0​ is out.  

### Describe the solution you'd like

finding the file and making it available for download

### Describe alternatives you've considered

none

### Please specify the version of Windows Subsystem for Android

2308.40000.3.0

**Comment by YT-Advanced** [comment]
You can use this ones:
https://github.com/YT-Advanced/WSAPackage

**Comment by Almighty188** [comment]
Thanks!
